### ISSUE TITLE
Make handle method to a instance property instead of static

### ISSUE THREAD

**Issue by thetutlage** [nrempel/adonis-scheduler#1]
Haven't tried it.

But by looking the example file https://github.com/nrempel/adonis-scheduler/blob/master/examples/app/Tasks/Example.js#L13 and the code, the `handle` method is a static property on the class, which simply defeats the purpose of creating a class.

I would suggest to make it an instance property and `make` the task class instance using `Ioc.make` on this line https://github.com/nrempel/adonis-scheduler/blob/master/src/Scheduler/index.js#L40.
## Benefits of Ioc.make

`Ioc.make` will create an instance of class and will inject any dependencies that class wants. For example.

``` javascript
class RemoveDisabledUsers {

  static get schedule() {
    return '*/1 * * * *';
  }

   static get inject () {
      return ['App/Model/User']
   }

   constructor (User) {
     this.User = User
   }

  * handle () {
     const removeUsers = yield this.User.query().where('status', 'disabled').delete()
   }

}

module.exports = RemoveDisabledUsers;
```

Above one is more helpful than having the `static handle`, coz I am able to inject my dependencies automatically.

Also wrap your `handle` method inside [co](https://www.npmjs.com/package/co). Which simply stays in the eco-system of AdonisJs by offering `ES2015` generators first approach.

**Comment by nrempel** [comment]
Thanks for the feedback!

I was fumbling a bit trying to come up with an idiomatic approach so this helps.

I'll make improvements soon.

**Comment by nrempel** [comment]
I've updated the library and published a new major version that support dependency injection.

I did not wrap the handle function with co since it is called by the node-schedule library which doesn't support co. (it doesn't need to)

**Comment by nrempel** [comment]
I've updated the library to support `yield` use using `co`
