### ISSUE TITLE
Start scheduler with adonis server

### ISSUE THREAD

**Issue by pirmax** [nrempel/adonis-scheduler#10]
Hi,

How to start scheduler when I type the command `adonis serve --dev` for example?

Thank you!

**Comment by ntvsx193** [comment]
Add this to `start/kernel.js`

```javascript
const scheduler = use('Adonis/Addons/Scheduler')
scheduler.run()
```

**Comment by pirmax** [comment]
Thanks @ntvsx193 !

**Comment by corneyl** [comment]
Could this be added to the readme? Very convenient!

**Comment by corneyl** [comment]
I actually found a better way, because if one starts the scheduler in `kernel.js`, it is also started when running an ace command.
1. Create a file in the start folder, e.g. `start-scheduler.js`, and add:
   ```
   'use strict'
   const Scheduler = use('Scheduler')
   Scheduler.run()
   ```
2. Add `.preLoad('start/start-scheduler')` to server.js:
   ```
   new Ignitor(require('@adonisjs/fold'))
     .appRoot(__dirname)
     .preLoad('start/start-scheduler')
     .fireHttpServer()
     .catch(console.error)
   ```

Now the scheduler is only started when running the server, not when running an ace command.

**Comment by abbasmoosavi** [comment]
> I actually found a better way, because if one starts the scheduler in `kernel.js`, it is also started when running an ace command.
> 
> 1. Create a file in the start folder, e.g. `start-scheduler.js`, and add:
>    ```
>    'use strict'
>    const Scheduler = use('Scheduler')
>    Scheduler.run()
>    ```
> 2. Add `.preLoad('start/start-scheduler')` to server.js:
>    ```
>    new Ignitor(require('@adonisjs/fold'))
>      .appRoot(__dirname)
>      .preLoad('start/start-scheduler')
>      .fireHttpServer()
>      .catch(console.error)
>    ```
> 
> Now the scheduler is only started when running the server, not when running an ace command.

Thanks, this worked for me!

**Comment by benknight** [comment]
> I actually found a better way, because if one starts the scheduler in `kernel.js`, it is also started when running an ace command.
> 
> 1. Create a file in the start folder, e.g. `start-scheduler.js`, and add:
>    ```
>    'use strict'
>    const Scheduler = use('Scheduler')
>    Scheduler.run()
>    ```
> 2. Add `.preLoad('start/start-scheduler')` to server.js:
>    ```
>    new Ignitor(require('@adonisjs/fold'))
>      .appRoot(__dirname)
>      .preLoad('start/start-scheduler')
>      .fireHttpServer()
>      .catch(console.error)
>    ```
> 
> Now the scheduler is only started when running the server, not when running an ace command.

One small problem with this approach is if you're starting the adonis server with the `--dev` flag like `adonis serve --dev` it will re-register the task on every file change, which will cause the task to run multiple times (an additional run every time a file is updated).
