### ISSUE TITLE
Which version is valid for Adonis 3.2?

### ISSUE THREAD

**Issue by GencBlakqori** [nrempel/adonis-scheduler#11]
I'm using Adonis3.2. I can't seem to make the library start. It's giving me this error when I'm typing ./ace:
```
SyntaxError: Unexpected identifier
../node_modules/adonis-scheduler/providers/SchedulerProvider.js (../node_modules/adonis-scheduler/providers/SchedulerProvider.js:1:1)
```
I added everything in the bootstrap/app.js file that was described, but can't make it work. Is 3.0.0 the right version for Adonis 3.2 ?

**Comment by nrempel** [comment]
The last published version for Adonis 3.x is `adonis-scheduler@2.1.2`

Let me know if that works.

**Comment by GencBlakqori** [comment]
@nrempel  Yes works! Thank you very much.

**Comment by nrempel** [comment]
Great ☺️
