### ISSUE TITLE
Run schedules without the ./ace command

### ISSUE THREAD

**Issue by GencBlakqori** [nrempel/adonis-scheduler#17]
How can I run the tasks without the ./ace command?
The idea is that I want to make it dependent on an env variable tu run it automatically, without having to type in the command.

**Comment by nrempel** [comment]
Hey @GencBlakqori, take a look here: https://github.com/nrempel/adonis-scheduler/issues/10

**Comment by GencBlakqori** [comment]
Works, thanks @nrempel
