### ISSUE TITLE
typo in src/Commands/Run.js

### ISSUE THREAD

**Issue by rbartholomay** [nrempel/adonis-scheduler#2]
Hi,

there is a typo in Run.js:

`'user strict';`

should be

`'use strict';`

And in my case handle should only work with co()...    But this can be an app specific problem..

**Comment by nrempel** [comment]
Thanks, I'll fix that.

What do you mean by it should only work with co()?

**Comment by rbartholomay** [comment]
Hi,

i n my case i must wrap my services inside co() to run this correctly. This is a problem of my application logic, so you can ignore this.

It will be great if you can add features like scheduler:stop and scheduler:stop <task> :-)

Bye

**Comment by nrempel** [comment]
Thanks @rbartholomay, I just updated the library to support `co`.

As of 2.1.0 you can use `yield` in the handle function.

Thanks!

**Comment by nrempel** [comment]
Closing the issue for now. Feel free to reopen it if you have more questions.
