### ISSUE TITLE
Run Scheduler with PM2

### ISSUE THREAD

**Issue by arwanfiles** [nrempel/adonis-scheduler#3]
Hi,
can I run adonisjs-scheduler as service with pm2?
or how to run scheduler on application start

regards,
Arwani

**Comment by linchpinstudios** [comment]
I'm not sure if it's the best way to run it, but I added the scheduler to the bootstrap for http before the `const Server = use('Adonis/Src/Server')` line.

```js
      /*
      |--------------------------------------------------------------------------
      | Run Scheduler
      |--------------------------------------------------------------------------
      |
      | Run the scheduler on boot of the web sever. 
      |
      */
      const Scheduler = use('Adonis/Addons/Scheduler')
      Scheduler.run()
```

**Comment by hoangmy92** [comment]
Did you try to run your process on binary mode?
http://pm2.keymetrics.io/docs/usage/process-management/#binary-code-execution

`pm2 start ./ace -- scheduler:run`

It should work :)

**Comment by nrempel** [comment]
Thanks @hoangmy92, that is what I would recommend.

Closing for now, feel free to re-open if there are any issues.

**Comment by altpoint** [comment]
Run with `pm2`  via `pm2 start ./ace -- run:scheduler` CPU overload to 100%

**Comment by prashanth1k** [comment]
My apologies to piggy-back on an old issue. Just wanted to point out that you would now use the following command instead..

`pm2 start ./ace -- run:scheduler`

You can also see the above when you go to adonis server directory and enter command -

`node ace --help`

**Comment by davidalexamos** [comment]
Thanks for the command `pm2 start ./ace -- run:scheduler`, it works perfect, but I am trying to do the same via the config file. I have tried this in the config but it does not start the app. 

`{
  name         : "megsapp-sim-card-process",
  cwd          : "/opt/megsapp-sim-card-process/",
  script       : "./ace",
  args         : "scheduler:run",
  error_file   : "/var/log/megsapp-sim-card-process/error.log",
  out_file     : "/var/log/megsapp-sim-card-process/out.log",
 }`

and

`{
  name         : "megsapp-sim-card-process",
  cwd          : "/opt/megsapp-sim-card-process/",
  script       : "node ace",
  args         : "scheduler:run",
  error_file   : "/var/log/megsapp-sim-card-process/error.log",
  out_file     : "/var/log/megsapp-sim-card-process/out.log",
 }`
