### ISSUE TITLE
Merge updates for support AdonisJS v4

### ISSUE THREAD

**Issue by ntvsx193** [nrempel/adonis-scheduler#6]
Hello.
I'm add support for AdonisJS v4 and send PR
It would be great if you merge this changes.
Thanks

https://github.com/nrempel/adonis-scheduler/pull/4
https://github.com/nrempel/adonis-scheduler/pull/5

**Comment by danilopolani** [comment]
+1 @nrempel

**Comment by nrempel** [comment]
Thank you @ntvsx193! I've just merged your changes and published to npm as version 3.0.0.

Your test suite passes but I haven't yet had time to test the provider in a real scenario.

If you have time, please test and let me know if you run into any issues.

Thanks all!

**Comment by nrempel** [comment]
@ntvsx193 I've made you a collaborator for this repository.

If you would like to push changes, please make sure you are diligent with test coverage and code quality. I hope that you can help me to keep this library up to date!

**Comment by ntvsx193** [comment]
@nrempel I would be update test, currently test states in progress.
Thx for access to contribute :)
