### ISSUE TITLE
AdonisJs Events wont fired

### ISSUE THREAD

**Issue by hanandika** [nrempel/adonis-scheduler#7]
scheduler running fine
i'm trying to attach to a Event in the end of task
but never catch in bootstrap/event.js

**Comment by nrempel** [comment]
The provider has just been updated to support adonis v4. Can you test adonis-scheduler@3.0.0 to see if it solves your problem?

**Comment by nrempel** [comment]
I'm closing this for now. If you test on the new version and still have the problem, please re-open the issue.
